### ISSUE TITLE
[!] Closing[-] Channel hopping failed: command failed: Operation not supported (-95)

### ISSUE THREAD

**Issue by CyberFlo2005** [DanMcInerney/wifijammer#105]
I installed Scapy and Python 2.7.16. on my raspberry Pi with raspbian. The script starts without any problems, but after ~5 seconds, this Error Appears. Is it an error from the script, or do I use the wrong antenna? (right now I'm using TP-Link: Model: TL-WN725N)

**Comment by foxtreat** [comment]
i have the same issue on three wireless cards including the Pi4 integrated Wifi,a TP link usb card and a Dlink one

**Comment by Sarlota-Duskova** [comment]
Did anybody solve that problem?
