### ISSUE TITLE
TypeError: argument 1 must be string, not NetworkInterface

### ISSUE THREAD

**Issue by Alii-isk** [DanMcInerney/wifijammer#112]
i keep getting this type error on line 287 when calling send(*)
TypeError: argument 1 must be string, not NetworkInterface

**Comment by Alii-isk** [comment]
i downgraded scapy version now it works just fine

**Comment by moraza** [comment]
> Hi, I'm having the same prob, may I know what version you downgraded it too?

Probably 2.5.1. See versions here: https://pypi.org/project/Scrapy/#history

**Comment by ghubz** [comment]
Same issue here, running scapy 2.4.5. Downgrading to any other version did not resolve the issue (or even upgrading to 2.5.0).
