### ISSUE TITLE
FOR ANYONE LOOKING FOR A WIFI JAMMER, USE MDK3, THIS REPO IS NO LONGER MANAGED

### ISSUE THREAD

**Issue by jurosic** [DanMcInerney/wifijammer#115]

**Comment by xenDE** [comment]
link?
charlesxsh/mdk3-master?

**Comment by DanMcInerney** [comment]
That's pretty true.

**Comment by Demetrio92** [comment]
meh. took 10 minutes to fix this fork: https://github.com/FirephoenixX02/wifijammer

And it works. Ubuntu 20.04, python3.8

**Comment by DanMcInerney** [comment]
Thanks @Demetrio92 I merged it.
