### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by ARCHOS31** [DanMcInerney/wifijammer#116]
File "/data/data/com.termux/files/home/wifijammer/wifijammer", line 114
    print '['+G+'*'+W+'] Finding the most powerful interface...'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by FirephoenixX02** [comment]
Fixed by https://github.com/DanMcInerney/wifijammer/pull/117
