### ISSUE TITLE
ImportError: No module named scapy.all

### ISSUE THREAD

**Issue by rudrakshya** [DanMcInerney/wifijammer#16]
When I execute the line
python wifijammer.py
It show me error
Traceback (most recent call last):
  File "wifijammer.py", line 5, in <module>
    from scapy.all import *
ImportError: No module named scapy.all

my python version is Python 2.7.3

**Comment by gconelhero** [comment]
Digite no terminal:
`sudo mkdir /usr/lib/python2.7/dist-packages/scapy`
`cd  /usr/lib/python3/dist-packages/`
`cp -avr scapy/* /usr/lib/python2.7/dist-packages/scapy`

Resolvido!

**Comment by ZAIRAWASIM** [comment]
Thank you sir but I can't get your point what you are saying

**Comment by h2th3k** [comment]
Works like a charm! Thanks bro @gconelhero

**Comment by DOKGMC** [comment]
Thank you @gconelhero worked like a charm

**Comment by Haxx** [comment]
Thank you @gconelhero! It did the the trick and your first post was quite straightforward for anyone who can read simple bash commands ;-)

**Comment by codebyAbhishekBharti** [comment]
Not working for me bro .
It is saying cp: cannot stat 'scapy/*': No such file or directory

SYSTEM:-
Linux mint

**Comment by gconelhero** [comment]
You have Python 2 installed? 
`python -m pip install scapy`
and after, cp.

**Comment by codebyAbhishekBharti** [comment]
@gconelhero yaa i have my python 2 installed in my system  and
 from scapy.all import *
 in python interpreter it is working fine.

LOOK HERE IS MY ISSUE:
When i am trying to execute the file using the the command:
sudo python wifijammer also tried using sudo python2 wifijammer
But it is returning the error:
Traceback (most recent call last):
File "wifijammer", line 6, in
from scapy.all import *
ImportError: No module named scapy.all

but when I run the from scapy.all import * in python interpreter it is working fine.

SYSTEM DETAILS
OS: Linux mint 20
Python 2.7.18

**Comment by codebyAbhishekBharti** [comment]
@gconelhero  @DanMcInerney  and also the error of **ImportError: No module named scapy.all** is happening when I am importing it as a root user else it I am importing as a normal user module is getting imported
