### ISSUE TITLE
Channel > 11 does not work

### ISSUE THREAD

**Issue by warna720** [DanMcInerney/wifijammer#21]
Great script!
It does not work with channels over 11.
sudo python2.7 wifijammer.py -c 13

**Comment by Manouchehri** [comment]
Change this line to channel 13.

https://github.com/DanMcInerney/wifijammer/blob/master/wifijammer.py?#L162

**Comment by DanMcInerney** [comment]
I added a --world option for increasing the max channel to 13 for non-N. Americans.
