### ISSUE TITLE
Explain some parts of script

### ISSUE THREAD

**Issue by RIMEH1** [DanMcInerney/wifijammer#25]
1- to the code is that the method is deauth after the output method or she is after 
 # For the first channel hop thru, do not deauth
                                    if first_pass == 1:
                                       
                                        time.sleep(1)
                                        continue
because I find in this link that the method is after output: http: //danmcinerney.org/how-to-kick-everyone-around-you-off-wifi-with-python/
2- Please could you explain to me the role of his instructions I am a beginner in python and ubuntu
-proc = Popen(['iw', 'dev', mon_iface, 'set', 'channel', monchannel], stdout=DN, stderr=PIPE)
and this please:
- if ch == monchannel:
                             deauth_pkt1 = Dot11(addr1=client, addr2=ap, addr3=ap)/Dot11Deauth()
                             deauth_pkt2 = Dot11(addr1=ap, addr2=client, addr3=client)/Dot11Deauth()
                             pkts.append(deauth_pkt1)
                             pkts.append(deauth_pkt2)
 
I need help please
thanks .

**Comment by DanMcInerney** [comment]
1. Not entirely sure what you're saying, but that part of the code handles the first pass through channels 1-11. It doesn't deauth at that time, instead it just collects accurate data of all routers/clients. Once the script has spent 1 second collecting data on each channel 1-11, then it moves on to skipping through channels as fast as it can and deauthing at the same time.

2. `proc = Popen(['iw', 'dev', mon_iface, 'set', 'channel', monchannel], stdout=DN, stderr=PIPE)` check out https://docs.python.org/2/library/subprocess.html#popen-constructor and http://stackoverflow.com/questions/12605498/how-to-use-subprocess-popen-python

The second line of code you listed just creates a Dot11 deauth packet using Scapy. Dot11 refers to 802.11, the wireless spec. Then it adds that packet to the list of packets it's going to send before changing channels.

**Comment by RIMEH1** [comment]
in this script we find:
output(err, monchannel)
if args.channel:
time.sleep(.05)
else:
# For the first channel hop thru, do not deauth
if first_pass == 1:
time.sleep(1)
continue
deauth(monchannel)

and in the lnk I find:
                        output(err, monchannel)
                        
                         deauth(monchannel)
                      
                         if args.channel:
                                    time.sleep(.05)
                         else:
                   # For the first channel hop thru, do not deauth
                                    if first_pass == 1:
                                        time.sleep(1)
                                        continue

the correct  is ?

**Comment by RIMEH1** [comment]
1- why you create only two packet Dot11

2- I tested your code I run this command sudo python deauth.py -a
B8:03:05:87:1E:46

but I notice that my connection is unsuccessful
please could help me so that I can disconnect a well- determined host without
disconnecting any leftovers.

thanks for your help.


2015-03-30 21:31 GMT+01:00 Dan McInerney <notifications@github.com>:

**Comment by DanMcInerney** [comment]
1. One deauth from client > access point and one deauth from access point > client for thoroughness.

2. -a is meant to deauth everyone that communicates with the target specified rather than just deauth a single target. This script wasn't really made for just deauthing one person, if you want to do that it's easier to use http://www.aircrack-ng.org/doku.php?id=deauthentication which can accomplish that in one line. The purpose of this script is mass deauth.

**Comment by DanMcInerney** [comment]
As for deauth() then code then output() or deauth then output() then code, the way it's written in the script now is the right way. Must've made a mistake earlier and fixed it. If deauth came prior to "if first_pass..." then it would deauth on the first pass which is not what we want.
