### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mozazoka** [DanMcInerney/wifijammer#27]
when i command wapiti this issue faces me :
"root@root:~# wapiti
Traceback (most recent call last):
  File "/usr/bin/wapiti", line 41, in  <module>
    lan.configure()
  File "/usr/lib/python2.7/dist-packages/wapitiCore/language/language.py", line 58, in configure
    lang = langCounty[:2]  # en
TypeError: 'NoneType' object has no attribute '__getitem__'
root@root:~# 

could someone help me pls?
Thanks in advance

**Comment by DanMcInerney** [comment]
Uh... this isn't the github account for wapiti. This is the github account
for wifijammer...

**Comment by mozazoka** [comment]
yea dude but i have seen sort of issues about the same problem here...I just hope solve it....thank you
