### ISSUE TITLE
Channel hopping failed: command failed: Invalid argument (-22)

### ISSUE THREAD

**Issue by BadHonk** [DanMcInerney/wifijammer#30]
Hi, I'm using kali linux in the 64bit version 1.1.0a within all updates till may 2015
on a virtual machine with VMWARE 11.

If I try   ./wifijammer.py   it works for a few seconds and the list of AP's is shown...
but then comes the error message in red colour in the first line that calls:
Channel hopping failed: command failed: Invalid argument (-22)

After that the script seems to stop working... and no deauthentication starts !

I'm using a alfa AWUS036NHR V2 Adapter and before starting wifijammer I switched
the adapter into monitor-mode with : airmon-ng start wlan0
The new virtual-adapter calls wlan0mon and works pretty good with the command:
airodump-ng wlan0mon

What can I do to solve the problem with the error-message?
(some restarts inkl. virtual machine does not help)

Please help me !!

**Comment by DanMcInerney** [comment]
Are you still having this issue? I'm wondering if it was caused by Kali (airmon really) switching to a different naming convention for monitor mode.
