### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by bee-san** [DanMcInerney/wifijammer#35]
Is it possible to give verbose output? So I know exactly what's happening as it runs?

**Comment by DanMcInerney** [comment]
Like a continual list of who the deauth packets are getting sent to?

**Comment by Leproide** [comment]
+1
Need for debug, on my raspberry this script wont work or work bad
sudo python wifijammer.py -s **:**:**:**:**:** -c 11 -a **:**:**:**:**:** -i wlan1

**Comment by MisterBianco** [comment]
I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and send me an issue at the repo above and Ill start work on it... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.
