### ISSUE TITLE
Could not execute "iwconfig"

### ISSUE THREAD

**Issue by damianmb** [DanMcInerney/wifijammer#46]
This is on mac after all the dependencies are installed.

**Comment by DanMcInerney** [comment]
Yeah doesn't work on mac atm.

**Comment by accuware** [comment]
Dat moment is looonggg

**Comment by rshopnil** [comment]
I'm experiencing this same problem in Arch. Not a seasoned developer, hope I didn't come as a Noob.

**Comment by quinn-brittain** [comment]
On arch, same issue as @rshopnil

**Comment by tieorange** [comment]
Still no way to run it on mac?
Will work well on Ubuntu VM?
