### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by damianmb** [DanMcInerney/wifijammer#47]
Hello, is it possible to create an android app with this functionality?

**Comment by MachinaAeternus** [comment]
http://forum.xda-developers.com/showthread.php?t=1282900
it's not free, though...

**Comment by damianmb** [comment]
I'ts not the same functionality.. is it? Do you know what jamming is?

**Comment by bryanj4** [comment]
Why don't you just import the proper libraries and program into qpython?
