### ISSUE TITLE
mac addresses are case-sensitive

### ISSUE THREAD

**Issue by tobyxdd** [DanMcInerney/wifijammer#48]
I found that users must use lower-case mac address for arguments or they aren't working at all. I suppose it should be case-insensitive?

**Comment by tobyxdd** [comment]
btw any news for 5G channel support? :smile:

**Comment by DanMcInerney** [comment]
You right. I think I fixed it by adding some .lower() to the argument strings with the goal of dealing with all MAC addresses in lowercase. 5G support is at a standstill until I or someone else can figure out how to channel hop using Scapy and 5G.
