### ISSUE TITLE
WiFiJammer on Openwrt 

### ISSUE THREAD

**Issue by atgeek** [DanMcInerney/wifijammer#49]
Since python and tcpdump are available for  openwrt, I've tried to run the wifijammer script, but iwconfig isn't more used on openwrt and was replaced by iw, the script clearly return that iwconfig wasn't found. Is possible modify it for use on openwrt?

**Comment by ramrattle** [comment]
I think only CC version of openwrt doesn't have iwconfing, you can always downgrade to BB or AA to use good old iwconfig

**Comment by atgeek** [comment]
I'm running openwrt version with iwconfig, but wifijammer say that iwconfig wasn't found

**Comment by brandonskerritt51** [comment]
Hi @atgeek ! Can you paste the output of iwconfig? and also, you're running a wifi jammer on OpenWRT? That's really cool!

**Comment by wokawoka** [comment]
Sorry for resuming this old issue, @atgeek , were you able to solve the problem at the end? 
I'm in the process of trying to do the same but apparently (according to what other people reported as well) the script gives the "iwconfig wasn't found" error on openwrt.
Thanks in advance!

**Comment by captainven** [comment]
Hey@atgeek can i know how you install wifijammer script on openwrt.thanks <3
