### ISSUE TITLE
Channel hopping failed: command failed: Operation not supported (-95)

### ISSUE THREAD

**Issue by pwrigley** [DanMcInerney/wifijammer#50]
I can get the module to start about 5% of the time.  the other 95% I get the error

Channel hopping failed: command failed: Operation not supported (-95)

I am quite new to to this so please explain in crayon if possible.

Thank you

**Comment by mrrfletcher** [comment]
i got that also

**Comment by tripledd** [comment]
I rec'd the error too, BUT, after I looked around a little bit I got it because the interface was NOT in monitor mode. Once I did airmon-ng start <interface>    Bob's your uncle. I hope this helps others out and thank you again to @DanMcInerney for an awesome little tool!
