### ISSUE TITLE
An option to jam Wifis only above xx db power

### ISSUE THREAD

**Issue by player66** [DanMcInerney/wifijammer#51]
Hello,

can you please add an option to jam all WIFIs above xx db power?
I have a signal of 99db which changes its mac address. 
I would like to jam everything above 97db and spare the rest.

Thanks!

**Comment by MisterBianco** [comment]
I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and I like your idea, send me an issue at the above repo and ill start work on it... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.
