### ISSUE TITLE
wifijammer on ARM computers

### ISSUE THREAD

**Issue by doge27** [DanMcInerney/wifijammer#64]
Is it possible to run this on Raspberry pi? 
Or ESP8266?

**Comment by phr34k0** [comment]
Yes possible bcause it's python driven. I run this on my smartphone.

**Comment by doge27** [comment]
Is it possible to install this on esp8266 or a nodemcu?

**Comment by phr34k0** [comment]
So long as there's aircrack-ng, your kernel has the drivers and patched for proper moniter mode for wireless card and python 2.7 installed, yes. Personally i find this useless as routers now comes with 5ghz spectrum. 2.4ghz are slowly getting deprecated by the minute.

**Comment by darkside2x** [comment]
Gents, I'm not the most experience with any of this so my question may be comical to you, but I've spent hours trying to make this work on my pi and can't get it to run. Hoping you can give a new coding student some advice. I have scapy-2.3.2 and wifijammer.py on my raspberry pi 3 using the python 2.7.9 shell. However, when I run wifijammer.py it tells me the following: 

Traceback (most recent call last):
  File "/home/pi/Desktop/wifijammer-master/wifijammer.py", line 5, in <module>
     from scapy.all import"
ImportError : No module named scapy.all

Really not sure how to get this to run...thanks in advance for any guidance you can give!

**Comment by phr34k0** [comment]
@darkside2x 

The import error indicates that you do not have Scapy installed on your Linux system.

sudo apt-get install python-scapy or http://scapy.net/ grab the latest source and 

unzip scapy-latest.zip
cd scapy-2.*
sudo python setup.py install

**Comment by darkside2x** [comment]
Thank you! So when I ran wifijammer on the pi and didn't get any errors, but it doesn't seem to do anything. it looks like it just skips a line in the python shell. It's not affecting any wifi, or showing any signs of life.. thoughts?

**Comment by darkside2x** [comment]
never mind I just transitioned to kali linux and got it working. great stuff!
