### ISSUE TITLE
skip MAC address jamming

### ISSUE THREAD

**Issue by radicspeter** [DanMcInerney/wifijammer#71]
I run your wifijammer.py in my Raspberry Pi 2 with usb Belkin F6D4050 v1 adapter, and every time when i add -s MAC_ADDRESS option it is deauth my given device too...

Anybody can confirm this bug? Or the problem is in my adapter?

**Comment by abdelbassetsf** [comment]
the script seems working fine exept the skip options , I think there is a problem in the program .

**Comment by jadolg** [comment]
I'm having the same issue. Somehow I get deauth too. Also I think It should work the other way too. (by not deauthenticating a client instead of just an AP)

**Comment by Mathisca** [comment]
6f0d7871abb095f2b0134c94b63554659c67d39a broke the skipping feature

**Comment by MisterBianco** [comment]
I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and see if I fixed it my version detects all your cards and adds them to the skip list although if you dont add the -d switch then you may still be deauthed.... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.
