### ISSUE TITLE
[-] Channel hopping failed: command failed: Device or resource busy (-16)

### ISSUE THREAD

**Issue by frakman1** [DanMcInerney/wifijammer#72]
While I am able to get this to work using no arguments `sudo python wifijammer.py` , I cannot seem to target a certain access point using `-a` (using MAC address or access point name) nor to  exclude a list of MAC addresses using `-s`. I get the error:

`[-] Channel hopping failed: command failed: Device or resource busy (-16)`

Also, when I try to target a certain channel using the `-c` option, I get a different behaviour. It's not an error message but it just sits there and doesn't so anything despite there being clients on the target channel:

`[+] wlan1 channel: 11
`

I am using a raspberry pi 3 running latest image and with a TP-Link  TL-WN722N with all dependencies installed (scapy, tcpdump etc)
`
 $ uname -a
`
`Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
`

Do you have any ideas or suggestions what might be going on?

**Comment by BrookMezgu** [comment]
Check if your WiFi adapter is in monitor mode and is not being used.... i.e not connected to an ap

**Comment by MisterBianco** [comment]
Device or resource busy is from the iw channel hopping section of the code.

I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and see if I fixed it... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.
