### ISSUE TITLE
it doesn't deauthenticate the clients after ap channel change ??? #67

### ISSUE THREAD

**Issue by hanbing88** [DanMcInerney/wifijammer#75]
it doesn't deauthenticate the clients after ap channel change ??? #67

**Comment by MisterBianco** [comment]
I have rewritten this tool https://github.com/MisterBianco/wifijammer-ng if you want to check it out and see if I fixed it... I am going to be doing some development and my version supports the 5ghz spectrum.

The only reason I didnt do a pull request is that the tool is very different from the original.
