### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by lodi-g** [DanMcInerney/wifijammer#77]
First of all, you did a great work.

However, is there any particular reason you would use Python 2 for this? 
Python 3 has been out since 2008, is widely supported and just really better than Py2 in a lot of way.

Thanks,

**Comment by MisterBianco** [comment]
Python 3 doesn't have scapy support so there is a reason behind choosing python 2. Python 3 will be better the day that library support is fixed. Until that day Py2 is better.

**Comment by lodi-g** [comment]
I don't think relying on an old library which runs on a deprecated language is a good idea tbh.

**Comment by DanMcInerney** [comment]
Well sure. But you're looking at two options: scapy or impacket. Neither of
which are python3. So there's not much choice.

**Comment by oldkingcone** [comment]
Python2. is still very well maintained by the community in my opinion.

**Comment by lodi-g** [comment]
That's where the problem lies imo. Why Python's community still supports an old, deprecated, featureless version of their 'favorite' language and then `import __future__` is beyond me.

**Comment by MisterBianco** [comment]
Well guess that's a personal stance :)
