### ISSUE TITLE
misleading title

### ISSUE THREAD

**Issue by digmorepaka** [DanMcInerney/wifijammer#83]
If you actualy dig a bit deeper you can see that this is not a jammer this is a deauther.
A jammer produces junk signal on the frequency of the communication you are trying to disable,
a deauther on the other hand is sending valid packets that are telling the device to disconnect.

**Comment by DanMcInerney** [comment]
Oh my, you're right! Here I was thinking this was actually jamming the frequencies but my god, I was wrong all along! It's actually a deauth script. Like, amazing detective work scoob.
