### ISSUE TITLE
[-] Channel hopping failed: command failed: Invalid argument (-22)

### ISSUE THREAD

**Issue by Nielske62** [DanMcInerney/wifijammer#84]
I tried to run 

> wifijammer.py --world 

on my Raspberry Pi 3b with Kali Linux but I got the following error:

> [-] Channel hopping failed: command failed: Invalid argument (-22)

This error occurs when the script hops from channel 11 to 12.
Anyone got any ideas how to fix this?

**Comment by ozskywalker** [comment]
If you run _iw list_ & _iw reg get_, do channels 12 & 13 show up as disabled or are you set to America with the country code?

I've hit issues before where on some wi-fi cards the channels are disabled irrespective of the regulatory domain, but then also had it where the wi-fi card has been set to America (i forget the actual country code itself) and therefore it would consider >11 as an invalid argument.

**Comment by Nielske62** [comment]
That issue fixed the error, thanks!
Another has shown up, when the channel reaches 13, it starts to loop from channel 1 to 13 fast ( `[+] wlan0 channel: [1-13]` )
Ideas?

**Comment by NuKESec** [comment]
i still get this error

**Comment by NuKESec** [comment]
country code is US, channels 1-14 are open

**Comment by NuKESec** [comment]
i just think this tool doesn't work. reset region to open ALL channels, and still i get the error. back to mdk3 i guess. fuck this dumbass tool
