### ISSUE TITLE
Stuck on dry-run

### ISSUE THREAD

**Issue by Fyb3roptik** [DanMcInerney/wifijammer#85]
I am using a kali linux live usb disk. Trying to run this and it stays on DRY-RUN and loops through the channels over and over for hours...is there something I am missing? Do I need to install kali onto the usb drive? Or does this work on live usb mode

**Comment by LFlare** [comment]
From what I can see, it's always going to output "DRY-RUN" even if it actually is running properly.

**Comment by DanMcInerney** [comment]
Fixed
