### ISSUE TITLE
[-] Channel hopping failed: command failed: Input/output error (-5)

### ISSUE THREAD

**Issue by twindragon6** [DanMcInerney/wifijammer#86]
It runs well for a few loops then crashes, clients appear to be continually detected but it's hard to say if the channel hopping is actually occurring. If it helps this happens on KALI Linux Live KDE 2018.1 with an Intel AC7260 card.

**Comment by MisterBianco** [comment]
I didn't realize the Intel ac7620 card was supported

**Comment by twindragon6** [comment]
Yeah, it's pretty cool! Below is some info.
https://wikidevi.com/wiki/Intel_Dual_Band_Wireless-AC_7260_(7260HMW)
https://wireless.wiki.kernel.org/en/users/Drivers/iwlwifi

**Comment by MisterBianco** [comment]
You can always throw up a stack Trace if one appears. If not some print debugging would be nice or you can try my wifijammer-ng repo
