### ISSUE TITLE
Error msg

### ISSUE THREAD

**Issue by ghost** [DanMcInerney/wifijammer#90]
![imagen](https://user-images.githubusercontent.com/33347027/39349464-5515ed00-49fb-11e8-98a6-76e115f64acd.png)

**Comment by chiwaka** [comment]
This appears by just doing 'python wifijammer.py -h' I don't know what it is caused by.

**Comment by dz-ikry** [comment]
Try to install scapy

**Comment by chiwaka** [comment]
It is. It must be when installing another version of scapy. Must require a version like scapy-2.0 instead of scapy-3.0 (FOR EXAMPLE!)
