### ISSUE TITLE
failed to start Network-Manager.service 

### ISSUE THREAD

**Issue by Md-afaaq** [DanMcInerney/wifijammer#96]
[   https://drive.google.com/open?id=13YA__u3dXaBOinoQlko_PdNAGJcFKP3G ] (url)

Plz check it out images

**Comment by Md-afaaq** [comment]
so whatz the solution...

**Comment by sanderv32** [comment]
Just remove [this line](https://github.com/DanMcInerney/wifijammer/blob/master/wifijammer#L466)
