### ISSUE TITLE
Doesn't work on Rasberry Pi 3b+

### ISSUE THREAD

**Issue by andowrannl** [DanMcInerney/wifijammer#97]
All that happens is the channels hop and rest of screen stays black doing nothing.

**Comment by DanMcInerney** [comment]
Yeah idk, I don't maintain this because theres better coded options now,
namely bettercap. Try bettercap and let me know how it goes I can probably
help there if that dev is slow to respond or doesnt help.

**Comment by andowrannl** [comment]
I was just running through bettercap then I saw your response haha, only diff is I don't see a way to deauth multiple AP at once, I just got it running though so maybe it can. Only change I had to make to get bettercap to work on the pi was to symlink /lib/ld-linux-armhf.so.3 TO /lib/ld-linux.so.3

Thanks a ton for such a quick reply. If i can figure out why yours no longer works on pi I will comment just for others or whatevs. :)
